config/routes.rb
Auto::Application.routes.draw do
  resources :lights

  get "remote/index"

end

app/models/light.rb
class Light < ActiveRecord::Base
  attr_accessible :guid, :name
end

app/models/projector.rb
require 'serialport'

class Projector
  
  def self.on
    serialport.write "PWR ON\r\n"
  end

  def self.off
    serialport.write "PWR OFF\r\n"
  end

  private

  def self.serialport
    @serialport ||= SerialPort.new "/dev/tty.usbserial", 9600
  rescue Errno::ENOENT
    raise CableDisconnected
  end

  class CableDisconnected < Exception; end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lights_controller.rb
class LightsController < ApplicationController
  # GET /lights
  # GET /lights.json
  def index
    @lights = Light.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lights }
    end
  end

  # GET /lights/1
  # GET /lights/1.json
  def show
    @light = Light.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @light }
    end
  end

  # GET /lights/new
  # GET /lights/new.json
  def new
    @light = Light.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @light }
    end
  end

  # GET /lights/1/edit
  def edit
    @light = Light.find(params[:id])
  end

  # POST /lights
  # POST /lights.json
  def create
    @light = Light.new(params[:light])

    respond_to do |format|
      if @light.save
        format.html { redirect_to @light, notice: 'Light was successfully created.' }
        format.json { render json: @light, status: :created, location: @light }
      else
        format.html { render action: "new" }
        format.json { render json: @light.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lights/1
  # PUT /lights/1.json
  def update
    @light = Light.find(params[:id])

    respond_to do |format|
      if @light.update_attributes(params[:light])
        format.html { redirect_to @light, notice: 'Light was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @light.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lights/1
  # DELETE /lights/1.json
  def destroy
    @light = Light.find(params[:id])
    @light.destroy

    respond_to do |format|
      format.html { redirect_to lights_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/remote_controller.rb
class RemoteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lights_helper.rb
module LightsHelper
end

app/helpers/remote_helper.rb
module RemoteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auto</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lights/_form.html.erb
<%= form_for(@light) do |f| %>
  <% if @light.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@light.errors.count, "error") %> prohibited this light from being saved:</h2>

      <ul>
      <% @light.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :guid %><br />
    <%= f.number_field :guid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lights/edit.html.erb
<h1>Editing light</h1>

<%= render 'form' %>

<%= link_to 'Show', @light %> |
<%= link_to 'Back', lights_path %>

app/views/lights/index.html.erb
<h1>Listing lights</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Guid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lights.each do |light| %>
  <tr>
    <td><%= light.name %></td>
    <td><%= light.guid %></td>
    <td><%= link_to 'Show', light %></td>
    <td><%= link_to 'Edit', edit_light_path(light) %></td>
    <td><%= link_to 'Destroy', light, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Light', new_light_path %>

app/views/lights/new.html.erb
<h1>New light</h1>

<%= render 'form' %>

<%= link_to 'Back', lights_path %>

app/views/lights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @light.name %>
</p>

<p>
  <b>Guid:</b>
  <%= @light.guid %>
</p>


<%= link_to 'Edit', edit_light_path(@light) %> |
<%= link_to 'Back', lights_path %>

app/views/remote/index.html.erb
<h1>Remote#index</h1>
<p>Find me in app/views/remote/index.html.erb</p>